### ISSUE TITLE
Monitor additional data plan

### ISSUE THREAD

**Issue by jcperil** [itsdrnoob/DataMonitor#75] opened 2022-11-14 16:06 UTC
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

I have a data plan with daily 2 GB limit. Occasionally, I add a separate 50 GB data plan valid upto the date of existing plan. Some days, I end up using extra data from this 50 GB and some days I don't. How do I track this extra plan? It is hard to manually keep track of that extra data usage everyday and harder to know when that 50 GB plan will be over.

### Describe the solution you'd like

Allow multiple plans by tracking the extra usage after the daily limit.

### Additional context

I hope the above description is coherent.

**Comment by itsdrnoob** [comment] 2022-11-14 16:09
Duplicate of #14

**Closed as completed by itsdrnoob** 2022-11-14 16:09 UTC
