### ISSUE TITLE
Mobile Data doesn't show in widget

### ISSUE THREAD

**Issue by seriousman64** [itsdrnoob/DataMonitor#152] opened 2023-03-20 07:21 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.2.0

### Steps to reproduce the bug

1. Go to widget settings on your mobile
2. Find Data Monitor widget and place it on the main screen

### Expected behavior

The widget should show both mobile and WI-FI data usage on it.

### Actual behavior

The widget shows only WI-FI usage, while mobile data is shown as 0,00MB. On the other hand, if you check this inside the app, everything is shown as expected 

### Screenshots/Screen recordings

![Screenshot_2023-03-20-08-18-25-178-edit_com miui home](https://user-images.githubusercontent.com/96442479/226272102-025f5444-e3e6-4bc1-ab62-15b4f91a371f.jpg)
![Screenshot_2023-03-20-08-19-42-370-edit_com drnoob datamonitor](https://user-images.githubusercontent.com/96442479/226272138-78f04b59-dcd9-4fff-af9a-7607b832f570.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Xiaomi Redmi Note 11

**Comment by itsdrnoob** [comment] 2023-03-20 07:26
Add a data plan to show mobile data usage in the widget. Issue's been fixed in beta build. 2eb03a0122172b1ef9b0d2912ec9fe14513611c2

Duplicate of #150.

**Closed as completed by itsdrnoob** 2023-03-20 07:26 UTC
