### ISSUE TITLE
Speed on to

### ISSUE THREAD

**Issue by rajarshikhatua100** [itsdrnoob/DataMonitor#19] opened 2022-07-30 02:14 UTC
You did as requested in #15 but we still have to open the notification panel to see the internet speed,see the screenshots I have marked that in screenshot, and also lower the widget and notification refresh interval- see [this](https://play.google.com/store/apps/details?id=com.internet.speed.meter.lite) app for reference
![20220730_073742](https://user-images.githubusercontent.com/77912617/181866341-021cf35e-d41b-4a1d-815d-2ce48a326b0a.jpg)
![20220730_073831](https://user-images.githubusercontent.com/77912617/181866350-6d6fef62-95d1-4342-a9f3-22964f6431b0.jpg)

**Comment by itsdrnoob** [comment] 2022-07-30 03:09
> You did as requested in #15 but we still have to open the notification panel to see the internet speed.

I assume you're taking about data usage because the app doesn't show internet speed at the moment.
If you want internet speed to be displayed instead, there's already an [issue](#11 ) opened regarding the same.

> lower the widget and notification refresh interval

Even if I add an option below 1 minute, your battery might not like the idea.

**Comment by rajarshikhatua100** [comment] 2022-07-30 03:15
oh sorry ,I don't noticed that the app currently doesn't show the speed, when you add please add my marked place, Thanks and sorry 😅

**Comment by itsdrnoob** [comment] 2022-07-30 03:26
No worries, and sure, notification showing internet speed is on my to-do list.

**Comment by itsdrnoob** [comment] 2022-07-30 03:26
Duplicate of #11

**Closed by itsdrnoob** 2022-07-30 03:26 UTC
