### ISSUE TITLE
Total amount is not same as the parts

### ISSUE THREAD

**Issue by Joppla** [itsdrnoob/DataMonitor#232] opened 2024-01-22 17:02 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.4.0

### Steps to reproduce the bug

Look in the daily usage 

### Expected behavior

Total amount is the same as the sum of the parts.

### Actual behavior

Sum (0.25+0.07+0.04+0.03+.0.00+0.00) is not the same as the total (1.18) See attachment 
![Verbuik](https://github.com/itsdrnoob/DataMonitor/assets/25467829/9790d282-56cd-4143-b6a2-dc16d36b1a76)

### Screenshots/Screen recordings

![Verbuik](https://github.com/itsdrnoob/DataMonitor/assets/25467829/5ab91abf-0094-4ff8-ad78-13e51e3367ef)

### Affected Android/Custom ROM version

android 13

### Affected device model

fairphone 4

**Comment by hueldoeu** [comment] 2024-01-25 17:50
before year 2024 data monitor from f-droid showed weird results, most of them were useless or empty. now, since my cable internet needs to be repaired, i use the sim-card mobile data 4G LTE mainly and the results of data monitor are great! i am just interested in usage of mobile data. now i need this for iphone too. suggestions?

**Comment by itsdrnoob** [comment] 2024-01-28 03:11
Duplicate of #126 
The data usage shown is exactly what's provided by the system. So I don't think there's much I can do here.

**Closed as completed** 2024-03-29 15:48 UTC
