### ISSUE TITLE
Some suggestions for improvement....

### ISSUE THREAD

**Issue by TheRealMystic** [itsdrnoob/DataMonitor#137] opened 2023-02-15 17:31 UTC
1. In the notification, please also include info on **Data remaining** in the plan cycle, as well as **No. of days remaining** in the plan.

2. In the App Usage section, please also show **Total Usage** (mobile data + wifi) per app, as an option.

3. In the App usage section, under select session, please also add the option to view usage per app during the **Plan Cycle**, i.e. add 'Plan Cycle' to the time period options.

4. On the Home screen, where you show the Data remaining, please also show the **No. of days remaining** in the plan cycle.

5. If only Mobile Data or WiFi is chosen to be shown in the notification (or widget), then 'Data usage Today' should still show the total (mobile data + wifi) usage.

**BUG 1**

If the plan cycle is changed from monthly to custom, the computation of data remaining isn't getting adjusted accordingly.

For example, try adding a monthly data plan of say 50 GB. Use some data, lets say 2 GB. The Home page correctly shows remaining data as 48 GB.

Now change the plan cycle to custom, where the start of the cycle is today (or some other day). Data remaining gets reset to the full 50 GB, instead of adjusting usage for the period already elapsed in the cycle, which in this case is 2 GB.

**BUG 2**

On rebooting the phone, the app crashes (after rebooting).

Thanks

**Comment by itsdrnoob** [comment] 2023-02-16 18:37
> BUG 1

Couldn't reproduce. Make sure the start and end date/time are set correctly.

> BUG 2

Probably related to #115. Fixed in v2.3.0

**Closed as completed** 2023-03-25 10:39 UTC
Labels: enhancement
