### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Teren4matrix** [itsdrnoob/DataMonitor#81] opened 2022-11-21 10:08 UTC
----------Start of crash----------
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 e.c.a.f.a.uncaughtException(Unknown Source:47),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
crash message: Unable to start receiver com.drnoob.datamonitor.utils.NotificationService$NotificationUpdater: java.lang.NumberFormatException: For input string: "69,10"

----------Crash logs----------
[android.app.ActivityThread.handleReceiver(ActivityThread.java:4468),
 android.app.ActivityThread.access$1700(ActivityThread.java:276),
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142),
 android.os.Handler.dispatchMessage(Handler.java:106),
 android.os.Looper.loopOnce(Looper.java:210),
 android.os.Looper.loop(Looper.java:299),
 android.app.ActivityThread.main(ActivityThread.java:8293),
 java.lang.reflect.Method.invoke(Native Method),
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556),
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)]

----------Device info----------
Device Manufacturer: Xiaomi
Device Brand: Xiaomi
Device Model: M2007J3SG
Device Codename: apollopro_global
Android version: 12, 31
SOC Model: SM8250

**Comment by itsdrnoob** [comment] 2022-11-21 10:57
Duplicate of #79

**Closed as completed** 2022-11-21 10:57 UTC
